### ISSUE TITLE
chkptstanr: Development Roadmap

### ISSUE THREAD

**Issue by venpopov** [venpopov/chkptstanr#1]
I have just take over the development of chkptstanr. There is a ton of cool features and fixes I want to add to the package, and this is a summary of my current ideas.

_This list is a work in progress_

## Hotfixes for major bugs (immediate priority)

The most important step is to resolve the current major bugs that prevent the package from functioning.

* [X] Resolve ['stan_code_path' not found when resuming fitting
](https://github.com/donaldRwilliams/chkptstanr/issues/8) 
     - this bug completely prevented the package from working _(solved - now resuming sampling works on all platforms)_
* [X] Resolve bug when specifying brms arguments such as data2, family, stanvars. ([here](https://github.com/donaldRwilliams/chkptstanr/issues/15), [here](https://discourse.mc-stan.org/t/checkpoint-brms-with-data2-argument/31426)) 
     - none of the dots args were being passed to the final brmsfit object, causing failure to convert the stan fit to brmsfit _(solved - now any argument that can be passed to brm works)_
* [x] #2
* [x] #8
* [ ] Release a v0.1.2 patch with the above fixes and submit to CRAN
* [ ] Submit to R-universe in the meantime while waiting for the transfer of maintainer status
     
## Other bugs
* [ ] Currently you cannot pass any arguments to cmdstanr if using chkpts_brms(). For example, save_warmup=T doesn't work. Similar to the issue above, but will require more systematic investigation of where to pass dots for full control
* [x] Incorrect error handling for "dividing iter_sampling by iter_per_chkpt must produce an integer" - wrong message, it should be for both warm-up and for sampling separately calculated
* [x] #6

## Improving stability 
* [X] Use github actions to continuously test the package with every change on most major platforms
* [ ] Add extensive unit tests
    - I have added some initial ones to demonstrated the above errors and when they are solved. They require compilation. Can I include executables for testing? Or is that against CRAN's rules? Maybe store them in an ignore folder and add a function to download them during testing?
* [ ] Clean up and refactor code for easier maintenance and development
   - chkpt_brms() and chkpt_stan() are almost identical, lots of the bugs are shared, so abstract a lot of this way
   - #11

## Improving efficiency
* [ ] Currently chkpt_brms() unecessarily regenerates the stancode and standata if sampling is resumed, which causes an overhead that can be easily avoided
* [ ] Check other places for optimizations
* [ ] Don't do any efficiency optimizations until the v0.1.2 hotfix release is out, so that later I can compare speed gains against a functioning version of the initial package

## New features
* [X] deprecated create_folder() and Do that automatically so that users only have to call chkpt_brms() or chkpt_stan() 
    - _(done - now you only need to specify the folder/path name in the path argument)_
* [x] add argument to predetermine a stopping checkpoint (asked for [here](https://github.com/donaldRwilliams/chkptstanr/issues/4))
    - _(done - see `stop_after` argument to chkpt_brms())_
* [ ] add ability to specify stopping conditions such as desired Rhat, minimum ESS, etc
* [x] #4
   - _(done for brms, not yet for stan; chkpt_brms now returns the fitted object, even after manual interruption, errors, or save_after=N - as long as you are past the warm-up phase)_
* [ ] add ability to pass a cmdstanmodel object to sample from 
   - see [here](https://discourse.mc-stan.org/t/chkptstanr-v0-2-0-alpha-checkpoint-brms-and-cmdstanr-sampling/34280/5?u=ven_popov)
* [ ] add function resume(fit), which can be applied to a `brmsfit` object to continue sampling from last checkpoint
* [ ] allow increasing the number of iterations and continuing to sample even if the previous fit completed
* [ ] attach a unique hash to the filenames generated by checkpoint for a specific model, so that one directory can be used for storing checkpoints of multiple models
* [ ] automatically reconstruct stanfit object when sampling finishes with chkpt_stan() to avoid having to reconstruct it manually via combine_chkpt_draws
* [ ] add easier to type alias for chkpt_brms() and chkpt_stan()
* [x] add an argument "restart" that restarts the sampling, but does not need a recompile

## Documentation
* [ ] Write new vignettes about new features

## Other changes
* [ ] make iter_sampling and iter_warmup argument names consistent with brms and deprecate existing arguments 
    - On second thought, they are consistent with cmdstanr. Which consistency to choose?
* [x] Increase default number of chains to 4 for consistency with `brms`

## Investigate
* [ ] #10
   -  also asked [here](https://github.com/donaldRwilliams/chkptstanr/issues/11#issuecomment-1568806510): 
* [ ] can I optimize the reading/writing of files?

**Comment by groceryheist** [comment]
> - [ ] Currently you cannot pass any arguments to cmdstanr if using chkpts_brms(). For example, save_warmup=T doesn't work. Similar to the issue above, but will require more systematic investigation of where to pass dots for full control.

Would this explain why the `refresh` parameter doesn't seem to work?

**Comment by venpopov** [comment]
> > * [ ]  Currently you cannot pass any arguments to cmdstanr if using chkpts_brms(). For example, save_warmup=T doesn't work. Similar to the issue above, but will require more systematic investigation of where to pass dots for full control.
> 
> Would this explain why the `refresh` parameter doesn't seem to work?

Yes. It's part of why I decided to rewrite everything, but other projects have gotten in the way.

**Comment by groceryheist** [comment]
Okay. It seems like this limitation kinda breaks the usefulness of this package. I think I would use this package a lot if it was useful and I could also help maintain it. 

From a cursory scan of the code it looks like we'll just want to add the `...` parameters to `cmd_args`. Does that seem correct?

**Comment by venpopov** [comment]
I agree, but there are much bigger problems with the package, namely that warmup is incorrectly implemented - see [here](https://github.com/venpopov/chkptstanr/issues/10). I picked up the package from the previous developer and solved most of the major issues before finding out that bigger issue, which requires a complete rewrite of the checkpointing implementation. That rewrite is in progress, and the problem you note is already solved in there. But it’s not ready to share. For now I do not recommend using this package, as noted in the alpha release notes.

**Comment by venpopov** [comment]
The … arguments are already passed to the brms constructor actually. But the package does not use brms to fit the model - just to construct the stan code and stan data, and then uses cmdstanr to fit the model, and refresh is a cmdstanr argument. You can’t just pass the dots to cmdstanr, because cmdstanr gives an error when it receives arguments that are not supported. So you need a way to determine which arguments to pass to brms for the code and data constructor, and which to pass to cmdstanr for the fitting. I\ve already done that in the ongoing rewrite of the package.

In the meantime, you should see progress when the ckpt_progress argument is true, which is by default, and it will printout the progress when every checkpoint is achieved, similar to the refresh argument.

**Comment by groceryheist** [comment]
I see. It sounds like you made a lot of progress on the new package  but it's not done yet. So I will wait for the new package. I'm pretty eager for this functionality so let me know how you can use help.
